# Generated by Django 5.1.1 on 2025-04-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('analysis_output', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('suggestion', models.TextField()),
                ('code_quality_score', models.IntegerField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
